# Generated by Django 4.2.1 on 2023-11-16 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_job_created_date_alter_job_job_city_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'verbose_name': '岗位信息', 'verbose_name_plural': '岗位信息'},
        ),
    ]
