# Generated by Django 4.2.1 on 2023-11-10 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='first_secore',
            new_name='first_score',
        ),
        migrations.AlterField(
            model_name='candidate',
            name='degree',
            field=models.CharField(blank=True, choices=[('本科', '本科'), ('硕士', '硕士'), ('博士', '博士'), ('其他', '其他')], max_length=135, verbose_name='学历'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='userid',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='应聘者ID'),
        ),
    ]
